name: Playwright Tests & Allure Report

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write # Necessário para a action peaceiris/actions-gh-pages fazer o push na branch gh-pages

jobs:
  test-and-report:
    name: Run Tests and Deploy Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Install Playwright Browsers
        run: uv run playwright install --with-deps

      - name: Run Playwright tests
        run: |
          uv run pytest --alluredir=allure-results --tracing=retain-on-failure --screenshot=only-on-failure --video=retain-on-failure
        continue-on-error: true # Continua a execução mesmo que os testes falhem para gerar o relatório
        env:
          # Carrega as credenciais e a URL base a partir dos segredos do repositório
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_USERNAME: ${{ secrets.USER_USERNAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

      - name: Generate Allure Report with history
        uses: simple-elf/allure-report-action@v1.7
        if: always() # Garante que o relatório seja gerado mesmo com falhas nos testes
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        if: always() # Garante que o deploy ocorra mesmo com falhas nos testes
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Store Allure results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 5 # Limpa o artefato após 5 dia para economizar espaço